import Head from 'next/head'
import Link from 'next/link';
import { Inter } from '@next/font/google'
import Card from '../components/Card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid grid-cols-4 gap-4">
          <Card>
            <Link href="/counter">Counter</Link>
          </Card>
          <Card>
            <Link href="">Guess The Number</Link>
          </Card>
          <Card>
            <Link href="">Telephone Formatter</Link>
          </Card>
          <Card>
            <Link href="">Light & Dark mode</Link>
          </Card>
        </div>

      </main>
    </>
  )
}
